    - name: Deploy to Netlify
      run: |
        npm install -g netlify-cli
        netlify deploy --prod --dir=build --site=your-site-id
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
