name: Deploy React App

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Deploy
      run: |
        echo "Deploy step here"
        # Add your deployment script or commands here
        # For example, if deploying to a hosting service like Vercel or Netlify, add the respective CLI commands here
        # Or you might want to upload the build artifacts to a server
